# This is a basic workflow to help you get started with Actions
name: Push button for qa
on:
  push:
    paths:
      - 'envs/regions/qa.tfvars'
      - '.github/workflows/dev.yml'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called “build”
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # Runs a single command using the runners shell
      - name: Initialize backend
        run: |
          terraform init -reconfigure
          terraform workspace select qa || terraform workspace new qa
      # Runs a set of commands using the runners shell
      - name: Execute apply
        run: |
          terraform destroy -var-file envs/regions/qa.tfvars  --auto-approve










